# Generated by Django 4.1.5 on 2023-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoriApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordrank',
            old_name='title',
            new_name='keyword',
        ),
        migrations.AlterField(
            model_name='keywordrank',
            name='count',
            field=models.IntegerField(),
        ),
    ]
